# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ed7c8e187f52d504a23b35b668aaf254de8d1f96da50d57480450926d54718da5e06f7dfde6298e309debba00ff0cb53778956ac5fcac6a7d18a3b420f731e

test:
  secret_key_base: 68d8da9bb79c33ce843503573e338bd9094b3bd09230534f7617bb3ae5331925cc9a226d7a3116c9b5264a6d6f98d9ca17107bc377fd3058de3271c098e13683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
